### ISSUE TITLE
can not fetch content when connecting with mysql

### ISSUE THREAD

**Issue by stevleibelt** [ohwgiles/sequeljoe#3]
I am using the latest aur.archlinux.org build (0.4.1).
When I connect to a mysql database (percona extension), I get the following entry in the log view when clicking on any table (try to check the content).

```
2015-07-29T11:46:27: SELECT * FROM "my_table" LIMIT 100 OFFSET 0
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"my_table" LIMIT 100 OFFSET 0' at line 1 QMYSQL: Unable to execute query
```

From the error point of view, it looks like the escaping is wrong.

```
SELECT * FROM "my_table" LIMIT 100 OFFSET 0
```

Should be

```
SELECT * FROM `my_table` LIMIT 100 OFFSET 0
```

Or?

**Comment by ohwgiles** [comment]
I used `SET GLOBAL sql_mode = 'ANSI_QUOTES'` (see https://dev.mysql.com/doc/refman/5.1/en/sql-mode.html#sqlmode_ansi_quotes) to keep variations between different sql engines to a minimum. Can you verify that your server supports this?

I had some difficulties making this work properly (1c01b61e3b74aecf00180e1168540381e35d4b5d) but it works on my mariadb instance

**Comment by stevleibelt** [comment]
@ohwgiles 

Thanks for the hint. Unfortunately, I can not set this since I can not guarantee, that everything would work with this setting.
Is it possible to make this configurable? All I can say is, that people who are working with SequelPro have no problems when working with our database. But I know this is a spare time project and all I can do is ask kindly (especially since my QT-skills are at beginner level/nearly not existent).

Anyways, thanks for the tool so far :+1: .

**Comment by ohwgiles** [comment]
@stevleibelt 
Of course the flag should not be global, but on a per-session basis so it won't affect your environment. Furthermore `SET GLOBAL` needs `SUPER` so that was probably why it wasn't working on a real system. I pushed a change (b45481b232a399a4dcf9e21e682019e8d75f87c0) that corrects this. Could you build from HEAD and verify that this helps?

**Comment by stevleibelt** [comment]
@ohwgiles 

This change is working like a charm. Thank you :-).

The next question is totally not connected to this issue. Can I force a refresh of a fetched result?
I'm having some tables with lots of changes on them. When I first load them (I am in the content view and I simple click on the table name), the content will be fetched. When I clock on an other table and click back on the first one, the result is taken from a cache. This approach is good in many cases, but it would be cool if I could trigger a "refresh view".

Again, thank you very much for this tool. Hope I can spend you a <put in your favorite drink here> sometime.

**Comment by ohwgiles** [comment]
@stevleibelt 

Great to hear it works.

I've been thinking about how to add such a button without overloading the already-crowded bar below the content view. It's not the most obvious, but for now you can trigger a refresh by clicking the "reset" filter button.

No problem, it's nice to have some user feedback
